version: '3.3'

services:
  webapi:
    image: webapi
    build:
      context: ./WebApi
      dockerfile: Dockerfile
  stockinstance:
    build:
      context: ./StockDatabase
      args:
        database_name: StockDatabase
    environment:
        ACCEPT_EULA: Y
    volumes:
      - type: bind
        source: ./StockDatabase/Database/Database/Data
        target: C:/database/Data
  priceinstance:
    build:
      context: ./PriceDatabase
      args:
        database_name: PriceDatabase
    environment:
        ACCEPT_EULA: Y
    volumes:
      - type: bind
        source: ./PriceDatabase/Database/Database/Data
        target: C:/database/Data
  webapplication:
    image: webapplication
    build:
      context: ./WebApplication
      dockerfile: Dockerfile
